# Generated by Django 5.2.6 on 2025-09-21 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_community_creator_community_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='created_by',
        ),
    ]
